version: '3'
services:

  app:
    user: "www-data"
    build: docker
    container_name: ${APP_NAME}-app
    volumes:
      - .:/www/app
      - /www/app/vendor
      - /www/app/storage
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  web:
    image: nginx:latest
    container_name: ${APP_NAME}-web
    ports:
      - "${WEB_EXTERNAL_PORT:-8000}:80"
    volumes:
      - .:/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT:-54320}:5432"

  redis:
      image: redis:alpine
      container_name: ${APP_NAME}-redis
      ports:
          - "${REDIS_EXTERNAL_PORT:-63790}:6379"
      environment:
          - REDIS_PASSWORD=${REDIS_PASSWORD}
      volumes:
          - redis-data:/data
          - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf

volumes:
    db-data:
    redis-data:
